"""005 — add surrogate `id` BIGSERIAL to session_summaries, eval_metrics, consent_registry.

Root cause
----------
Migrations 0001–0004 created session_summaries, eval_metrics, and
consent_registry with *natural* primary keys (session_id / speaker_label).
The SQLAlchemy ORM models (models.py) however declare `id` as their primary
key column (BigInteger, autoincrement=True) — the standard pattern used by
every other table in the schema.

The mismatch caused SQLAlchemy's pg_insert(Model) helper to emit

    RETURNING session_summaries.id

after every upsert, which Postgres rejected with:

    asyncpg.exceptions.UndefinedColumnError: column session_summaries.id
    does not exist

Fix strategy
------------
1. supabase_client.py — *immediate runtime fix* (applied separately):
   swap pg_insert(Model) → pg_insert(Model.__table__) for the three
   affected upsert helpers.  Table-level inserts never auto-append RETURNING,
   so the error disappears regardless of DB state.

2. This migration — *long-term schema alignment*:
   Add `id BIGSERIAL` to the three tables so the DB column actually exists.
   The existing natural-key PK constraint is preserved; id becomes a
   UNIQUE NOT NULL surrogate that the ORM can use for RETURNING / identity
   tracking without displacing the ON CONFLICT target.

   After this migration runs, you can also revert supabase_client.py back to
   pg_insert(Model) if you prefer — RETURNING session_summaries.id will now
   succeed.  Keeping pg_insert(Model.__table__) is equally valid and avoids
   any future RETURNING surprise.

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-01
"""

import sqlalchemy as sa
from alembic import op

# ---------------------------------------------------------------------------
revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None
# ---------------------------------------------------------------------------


def upgrade() -> None:
    # ── session_summaries ─────────────────────────────────────────────────────
    # Add id as a BIGSERIAL column with a UNIQUE constraint.
    # session_id remains the PRIMARY KEY and the ON CONFLICT target for upserts.
    op.add_column(
        "session_summaries",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),   # GENERATED BY DEFAULT AS IDENTITY
            nullable=False,
        ),
    )
    op.create_unique_constraint("uq_session_summaries_id", "session_summaries", ["id"])

    # ── eval_metrics ──────────────────────────────────────────────────────────
    op.add_column(
        "eval_metrics",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
        ),
    )
    op.create_unique_constraint("uq_eval_metrics_id", "eval_metrics", ["id"])

    # ── consent_registry ──────────────────────────────────────────────────────
    op.add_column(
        "consent_registry",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
        ),
    )
    op.create_unique_constraint("uq_consent_registry_id", "consent_registry", ["id"])


def downgrade() -> None:
    op.drop_constraint("uq_consent_registry_id",  "consent_registry",  type_="unique")
    op.drop_column("consent_registry",  "id")

    op.drop_constraint("uq_eval_metrics_id",       "eval_metrics",      type_="unique")
    op.drop_column("eval_metrics",      "id")

    op.drop_constraint("uq_session_summaries_id",  "session_summaries", type_="unique")
    op.drop_column("session_summaries", "id")